### ISSUE TITLE
Use tempstore functionality instead of DB storage

### ISSUE THREAD

**Issue by juanolalla** [juanolalla/content_lock#5]
@dawehner proposed this improvement in: https://www.drupal.org/node/2606858#comment-11817124

> Conceptually this really reminds me of the locking feature in views. We are using the tempstore functionality in the user module for that (service: ```user.shared_tempstore```), which should make all the DB storage here redundant.

**Comment by chrfritsch** [comment]
Here is the d.o. issue https://www.drupal.org/node/2852191

**Comment by juanolalla** [comment]
Thanks @chrfritsch!
