### ISSUE TITLE
Route content_lock_timeout.settings_form should require "administer content lock" permission

### ISSUE THREAD

**Issue by juanolalla** [juanolalla/content_lock#8]
As @martincollar mentioned in https://www.drupal.org/node/2606858#comment-11832539:

Route content_lock_timeout.settings_form should require "administer content lock" permission instead of "access administration pages". For example with this permission my editors (they have access to admin pages) will be able to setup timeout for locks.

**Comment by chrfritsch** [comment]
Here is the d.o. issue https://www.drupal.org/node/2852188

**Comment by chrfritsch** [comment]
Fixed

**Comment by juanolalla** [comment]
Thanks @chrfritsch!
