### ISSUE TITLE
Support any entity type without module dependencies

### ISSUE THREAD

**Issue by juanolalla** [juanolalla/content_lock#9]
As @dawehner explained in https://www.drupal.org/node/2606858#comment-11817124, and @chrfritsch pointed out in https://www.drupal.org/node/2606858#comment-11831036, there is no reason for not supporting any entity type, instead of specifically supporting and so for duplicating the code for node, taxonomy_term and block content entity types. The module should not have a hard dependency on the block_content module, neither with any other specific entity type module.

> As a follow up we could move this logic into a new handler type on entity types, so you can implement your own logic if needed. inline_entity_form does something similar.

**Comment by dawehner** [comment]
In case you have any additional question, feel free to ask. I'm happy to help, even I don't need this particular feature right now

**Comment by juanolalla** [comment]
Thanks! We don't need this improvement right now either but I do think it's important for the future of this module, so I'll try to find some time to refactor this and I'll ask you if I feel I need some guidance :)

**Comment by chrfritsch** [comment]
Here is the d.o. issue for that

https://www.drupal.org/node/2852187

**Comment by juanolalla** [comment]
Thanks!!
